### PR TITLE
Fix windows support

### LINKED ISSUE #89: Add Windows support
Hi, I´m facing this error with Shot version 3.1.0 when running the command gradlew executeScreenshotTests on windows:
adb.exe: unknown command rm
image

### PR DESCRIPTION
**Pull request by ViniciusGuardieiroSousa**
The result of adb devices command on Windows is the list of devices and a Carriage Return character, which is causing trouble for tests on Windows.
To solve this in the methods pullScreenshots and clearScreenshots I verify if the device string is the carriage return character, for this, I create a function isCarriageReturnASCII, this function receive the device as parameter and check if the charAt(0) isn't the CR_ASCII_DECIMAL (a constant with the CR in decimal) to run the commands for each method.

I don't create the unit tests for this change, I already try on mac and pass

Closes #89

### CODE REVIEW

**Comment by pedrovgs** [comment]
Thanks for your PR @ViniciusGuardieiroSousa ! I'll take a look in two weeks if you don't mind. Right now I don't have time to review this.

**Comment by ViniciusGuardieiroSousa** [comment]
> Thanks for your PR @ViniciusGuardieiroSousa ! I'll take a look in two weeks if you don't mind. Right now I don't have time to review this.
On bitrise i had this problem: Could not find com.karumi:shot:3.1.1-SNAPSHOT, but I saw in your code that you are using com.karumi: shot: 3.1.1-SNAPSHOT, so if you need any change to work on the bitrise, let me know to correct and solve this block

**Comment by pedrovgs** [comment]
Hi @ViniciusGuardieiroSousa I'm taking a look at the CI build and seems there is something wrong with the main dependency installation. Anyway, looking at the code I'm wondering if you could change the fix to avoid the generation of a device instance using the Carriage Return character instead of checking all around the app if the device is not a valid one. Could you also please add code coverage to the fix once it is finished? As soon as we implement this solution we'll see what's going on with the CI build. Thank you for your collaboration 😃

File: core/src/main/scala/com/karumi/shot/android/Adb.scala [hunk 1]
```diff
@@ -9,13 +9,28 @@ object Adb {
 }
 
 class Adb {
+
+  final val CR_ASCII_DECIMAL = 13
+
   def devices: List[String] = {
-    executeAdbCommandWithResult("devices").split('\n').toList.drop(1).map {
+    listWithoutCarriageReturn(executeAdbCommandWithResult("devices").split('\n').toList.drop(1).map {
```
Comment (pedrovgs) [inline core/src/main/scala/com/karumi/shot/android/Adb.scala]: Instead of doing this why don't you filter the lines you don't want?

File: core/src/main/scala/com/karumi/shot/android/Adb.scala [hunk 2]
```diff
@@ -9,13 +9,28 @@ object Adb {
...
+    var result = List[String]()
+    strings.foreach{
+      line =>
+        if(!isCarriageReturnASCII(line))
+          result = line :: result
     }
+    result
   }
 
+  def isCarriageReturnASCII(device: String): Boolean = device.charAt(0) == CR_ASCII_DECIMAL
```
Comment (pedrovgs) [inline core/src/main/scala/com/karumi/shot/android/Adb.scala]: Any function you add should be private.

File: core/src/main/scala/com/karumi/shot/android/Adb.scala (hunk 1 above)
Comment (ViniciusGuardieiroSousa) [reply core/src/main/scala/com/karumi/shot/android/Adb.scala]: I solve the request, I don't test the changes I will do this later and create the tests for this change, I check and don't have tests for the Adb class

**Comment by ViniciusGuardieiroSousa** [comment]
I make your changes, on bitrise I have problem with this task "testDebugComposer", I run this task and I had this problem:  Exception is:
org.gradle.execution.TaskSelectionException: Task 'testDebugComposer' not found in root project 'Shot'.  Could you help me solve it? And I didn't find the test class to Adb class to implement the corresponding tests for the changes I've made

**Comment by Serchinastico** [comment]
Hey @ViniciusGuardieiroSousa,

I was just reviewing your PR and I found why the CI wasn't passing. Looks like you changed the format of some files (namely, `Adb.scala` and `Shot.scala`). We are running [`scalafmt`](https://scalameta.org/scalafmt/) and it didn't like it 😅 . That caused the Shot artifact to not be created and so, the screenshot tests to fail.

I'm sending you a git patch so that you can apply it to your branch: https://gist.github.com/Serchinastico/a2864391bfd91e6c9364d64121c8772e

Don't forget to mention us whenever you do so and we can see if it worked.

Thank you for your contribution!

**Comment by ViniciusGuardieiroSousa** [comment]
> Hey @ViniciusGuardieiroSousa,
> 
> I was just reviewing your PR and I found why the CI wasn't passing. Looks like you changed the format of some files (namely, `Adb.scala` and `Shot.scala`). We are running [`scalafmt`](https://scalameta.org/scalafmt/) and it didn't like it 😅 . That caused the Shot artifact to not be created and so, the screenshot tests to fail.
> 
> I'm sending you a git patch so that you can apply it to your branch: https://gist.github.com/Serchinastico/a2864391bfd91e6c9364d64121c8772e
> 
> Don't forget to mention us whenever you do so and we can see if it worked.
> 
> Thank you for your contribution!

I apply you patch.diff, and know the problem with the CI is other, Task 'greenDebugExecuteScreenshotTests' not found in root project 'shot-consumer-flavors', can you help me to solve this question?

**Comment by Serchinastico** [comment]
I was afraid this was going to happen. We'll have to wait for #95 to be merged into master first. 

Just for context, it is a PR that comes with flavors support and to test it we had to change our CI steps. Because the CI configuration is not in the repository itself, it affects other PRs like yours. Let us sort it out from our end!

**Comment by pedrovgs** [comment]
@Serchinastico @ViniciusGuardieiroSousa I've merged the branch I had pending so you can update this branch with master and continue working on it with the CI tool working as expected.

**Comment by ViniciusGuardieiroSousa** [comment]
> @Serchinastico @ViniciusGuardieiroSousa I've merged the branch I had pending so you can update this branch with master and continue working on it with the CI tool working as expected.

@pedrovgs  @Serchinastico, thank you for the help, now the code passed on the CI, I need to make more changes?

**Comment by pedrovgs** [comment]
This is working like a charm right now!! Thank you @ViniciusGuardieiroSousa for your PR and @Serchinastico for your help.
